### ISSUE TITLE
crashes if a directory name contains spaces

### ISSUE THREAD

**Issue by tbrodbeck** [systemctl603/system-viewer#1]
Hi. Nice extension. but i realized that it crashes if a directory name contains spaces.
<img width="269" alt="Screen Shot 2021-11-28 at 11 42 03" src="https://user-images.githubusercontent.com/24418160/143764541-a11ac495-2735-417c-b9e3-3ddd10e46021.png">

**Comment by systemctl603** [comment]
I've started working on the issue, but i'm running into a problem with the actual opening of the file, so it might take a bit of time to fix

**Comment by systemctl603** [comment]
I rewrote the opening code to use [open](https://www.npmjs.com/package/open), and it seemed to have worked.
